### ISSUE TITLE
Playing multiple tracks at once.

### ISSUE THREAD

**Issue by psdwizzard** [popeen/Popeens-DSub#48] opened 2016-09-07 01:45 UTC
I have the beta of the server installed. It will play longer tracks fine. But the shorter tracks it sounds like as soon as the it cache the next track it starts playing it with no way to pause it. It starts playing immediately upon opening several tracks at once.

I am running this on a Nexus 6P with android 7

**Comment by popeen** [comment] 2016-09-23 20:06
I am not sure I understand what the problem is, does it start to play every file it caches?

**Comment by hjone72** [comment] 2016-09-27 03:02
I am also having this issue. It only seems to be happening when I build from source, so I'm assuming I'm doing something wrong.

When I open the app it immediately starts playing whatever book I last had going, however the play icon in the bottom bar doesn't signal that. If I then wait a few moments the next track also begins playing.

Furthermore, it seems to re-cache the files each time I open the app.

After looking into it, looks like we will need these/some of these changes brought over to this fork. I've made a few of the changes so far and it has fixed it for me.

https://github.com/daneren2005/Subsonic/commit/a05ecac6a649b11c8d6f277514dbc72d9bea674b

**Comment by psdwizzard** [comment] 2016-09-30 01:44
I just updated and for the few mins I used it, it has seemed fine. I will do more extensive testing over the next few days.

**Comment by popeen** [comment] 2016-09-30 16:36
Great, I'm closing this for now but let me know if the problem comes back

**Closed as completed by popeen** 2016-09-30 16:36 UTC
