### ISSUE TITLE
Android app crashes on connect to server

### ISSUE THREAD

**Issue by Tonbery7** [popeen/Popeens-DSub#42] opened 2016-06-02 11:44 UTC
The android app crashes on connect to the booksonic server:

> **Booksonic Server (docker-version):**
> Version   1.1.beta1 – February 7, 2016
> Server    Apache Tomcat/8.5.0, java 1.8.0_72-internal, Linux (57.2 MB / 196.0 MB)
> **Booksonic App:**
> Version 1.0.7

The booksonic server itself and the web-interface work without issues (library, media-scanning, playback) and is accessible externally.
I access the server externally through a squid reverse proxy with ssl, but the app also crashes by accessing the server internally, bypassing the reverse proxy.

The docker-server publishes the web-interface on port 8080, so my URL would be 

> https://<host>:8080/booksonic

The app connects successfully on "Test connection" (external and internal), so general connectivity exists. But as soon as is try to browse the library with the app it crashes without any error-message.
I testet this with:

> Sony Xperia Z3 Tablet Compact, Android 6.0.1
> Nexus 7 (2012), Android 5.1.1

I also run a similar setup (external access through reverse proxy) with my Subsonic server + DSub App without any issues

I also testet this with the **windows-version** of the booksonic server, which **works without crash**. Apparently the docker/linux-version of the server causes the app to crash

**Comment by popeen** [comment] 2016-06-02 16:52
Interesting,

If you use DSub to connect to the Booksonic server does it work any better?
How about the Booksonic app connected to your Subsonic server?

You can open the app without it crashing as long as you don't go to the
library, correct? If so please send me a log file, I'm not sure it will
help but you never know, there might be something that helps pinpoint the
problem, you can send the log from the top right menu.

I'll see if I can reproduce the problem and hopefully learn some more about
what's causing it.

**Comment by popeen** [comment] 2016-06-02 17:00
Just saw your note about it being a problem with the server on Linux, that's good to know so thanks for adding it.

**Comment by Tonbery7** [comment] 2016-06-02 18:27
Ok:

> Connecting DSub -> Booksonic-Server -> **works**
> Connecting Booksonic (App) -> Subsonic-Server -> **works**

I can't start the Booksonic-App after i configured it with my Booksonic-Server, because it crashes on start from that point on, i couldn't even send you a log-file from within the app, i have to delete the app-data to use it again, but luckily i found a log-file:

`Android API level: 23`
`Subsonic version name: 1.0.7`
`Subsonic version code: 9 java.lang.IllegalArgumentException: Invalid % sequence: %RR in query at` `index 70: http://<host>:8080/booksonic/rest/ping.view?u=<user>&p=`
`<pwd>&v=1.2.0&c=booksonic&f=json`

```
  `at java.net.URI.create(URI.java:734)`
  `at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:80)`
  `at github.popeen.dsub.util.KakaduaUtil.http_get_contents(KakaduaUtil.java:93)`
  `at github.popeen.dsub.activity.SubsonicActivity$2.run(SubsonicActivity.java:226)`
  `at java.lang.Thread.run(Thread.java:818)`
```

`I redacted it a little <host>, <user> and <pwd> are only placeholders. They have the following characteristics:`

> host: standard IP (xx.xx.xx.xx)
> user: only upper-/lower-case letters
> pwd: **i think this is the problem, because i have '%' and '&' in the password, and in the log-file it isn't url-encoded, if i login to the booksonic-server with another password it works without error and doesn't crash. interestingly that new password does contain a '&' but no '%'**

I think the exception get's thrown, because the method _java.net.URI.create_ has issues with my password, because it doesn't get encoded.

Hope this helps.

**Comment by popeen** [comment] 2016-06-02 20:21
OK, yah that sounds like it might be right. Since it works in DSub and has
to do with the ping endpoint I'm pretty sure the problem is with the bit of
code that checks if it's a Booksonic server or not. I'll try and get a fix
out before the end of the week (probably Saturday) so you can get your
password back.

It is a bit weird tho because I don't get the same bug on my servers
(Windows and docker on Ubuntu) but even so I'm pretty sure you are right
about the missing urlencoding being the problem. That would explain why it
crashes as soon as you open the app after it has been configured.

Great reporting by the way, always happy when people write down as much
info as possible instead of just "it doesn't work", makes my job so much
easier, in this case even more so since you most likely found the problem
yourself.

**Comment by popeen** [comment] 2016-06-06 21:44
I just uploaded Booksonic 1.0.8 to the Play Store (might take a couple of hours before Google publish it), I think this will solve your problem so I'm closing this issue. Should it still remain after you get the update just let me know and I'll reopen it and have another look.

**Closed as completed by popeen** 2016-06-06 21:44 UTC
Labels: bug

**Comment by Tonbery7** [comment] 2016-06-07 03:18
Works, thank you very much!

**Comment by popeen** [comment] 2016-06-07 06:17
No problem, glad it works for you
