### ISSUE TITLE
Variable speed playback with pitch correction

### ISSUE THREAD

**Issue by apastuszak** [popeen/Popeens-DSub#24] opened 2015-12-28 23:15 UTC
This is a must.  All my other audiobook and podcast players support this.  I usually listen to books at 1.7x.

**Comment by popeen** [comment] 2015-12-29 00:02
Yeah, I agree with you. It's planned.
Thanks for coming with suggestions

I'm closing this because it is a duplicate of #20

**Closed as completed** 2015-12-29 00:03 UTC
Labels: duplicate, enhancement
